include: package:flutter_lints/flutter.yaml

analyzer:
  # Modo estricto para type safety
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  # Errores críticos
  errors:
    # Type safety
    invalid_assignment: error
    missing_return: error
    missing_required_param: error
    invalid_null_aware_operator: error

    # Code quality
    dead_code: warning
    unused_element: warning
    unused_import: warning
    unused_local_variable: warning
    deprecated_member_use: warning

    # Documentación (info para no bloquear desarrollo)
    public_member_api_docs: info

  # Excluir archivos generados
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "**/build/**"
    - "**/.dart_tool/**"

linter:
  rules:
    # ============================================
    # NAMING CONVENTIONS
    # ============================================
    # Identificadores descriptivos (evita variables de una letra)
    non_constant_identifier_names: true
    constant_identifier_names: true
    camel_case_types: true
    camel_case_extensions: true
    file_names: true
    library_names: true
    library_prefixes: true
    package_names: true

    # ============================================
    # TYPE SAFETY (evitar dynamic)
    # ============================================
    avoid_dynamic_calls: true
    avoid_annotating_with_dynamic: true
    always_declare_return_types: true
    type_annotate_public_apis: true
    prefer_typing_uninitialized_variables: true
    omit_local_variable_types: false
    always_specify_types: false  # Demasiado estricto, mejor inferencia

    # ============================================
    # PERFORMANCE
    # ============================================
    # Evitar rebuilds innecesarios
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # Evitar operaciones costosas
    avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sized_box_shrink_expand: true

    # Evitar lambdas innecesarias (afecta rendimiento)
    unnecessary_lambdas: true
    prefer_function_declarations_over_variables: true

    # ============================================
    # WIDGETS Y FLUTTER ESPECÍFICO
    # ============================================
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    use_decorated_box: true
    use_colored_box: true
    prefer_single_quotes: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    no_logic_in_create_state: true

    # ============================================
    # NULL SAFETY
    # ============================================
    avoid_null_checks_in_equality_operators: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    prefer_if_null_operators: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    cast_nullable_to_non_nullable: true
    avoid_returning_null_for_void: true

    # ============================================
    # CODE QUALITY
    # ============================================
    # Evitar código peligroso
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    avoid_returning_null_for_future: true
    avoid_void_async: true
    avoid_positional_boolean_parameters: true
    avoid_catching_errors: true
    avoid_catches_without_on_clauses: true
    only_throw_errors: true

    # Control de flujo
    control_flow_in_finally: true
    throw_in_finally: true
    exhaustive_cases: true
    no_default_cases: false

    # Preferencias de estilo
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_void_to_null: true
    prefer_generic_function_type_aliases: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_conditional_assignment: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_mixin: true

    # Código innecesario
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true

    # Evitar código redundante o confuso
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true

    # Imports
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    directives_ordering: true
    implementation_imports: true
    library_annotations: true

    # ============================================
    # DOCUMENTACIÓN
    # ============================================
    public_member_api_docs: true
    slash_for_doc_comments: true
    package_api_docs: true
    comment_references: true

    # ============================================
    # FORMATO Y ESTILO
    # ============================================
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    leading_newlines_in_multiline_strings: true
    lines_longer_than_80_chars: false  # Flexibilidad en líneas largas
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_runtimeType_toString: true
    noop_primitive_operations: true

    # Trailing commas para mejor formato
    require_trailing_commas: true

    # ============================================
    # TESTING
    # ============================================
    test_types_in_equals: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # ============================================
    # SEGURIDAD
    # ============================================
    secure_pubspec_urls: true
    depend_on_referenced_packages: true
    use_super_parameters: true
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    eol_at_end_of_file: true
    hash_and_equals: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    no_self_assignments: true
    no_wildcard_variable_uses: true
    overridden_fields: true
    parameter_assignments: true
    provide_deprecation_message: true
    recursive_getters: true
    tighten_type_of_initializing_formals: true
    unawaited_futures: true
    unnecessary_breaks: true
    unreachable_from_main: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_string_in_part_of_directives: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    void_checks: true
